### PR TITLE
Update to newest vinyl for gulp 4 support

### PR DESCRIPTION
**Pull request by phated**
@UltCombo can you get this merged and published right away?  A lot of people are having trouble with the new alpha of gulp 4 due to outdated vinyl deps.

### CODE REVIEW

**Comment by erikkemperman** [comment]
Need to check why tests are failing, but +1 for the vinyl upgrade!

**Comment by namoscato** [comment]
It looks like the [AppVeyor failure](https://ci.appveyor.com/project/floatdrop/gulp-watch/build/80/job/oi9t7rb248j3pf9f#L16) is caused by the latest version of `npm@5.6.0` running on an older version of Node v0.12. While I did not test this on Windows, I was able to replicate the issue on my MacBook, and the issue was resolved by downgrading to `npm@2.15.11`, which is [bundled with](https://nodejs.org/en/download/releases/) Node v0.12.

I am unfamiliar with AppVeyor, but we might look at removing:

https://github.com/floatdrop/gulp-watch/blob/608c7aa47ebe3d19b55fee703b30d5245a7229ee/appveyor.yml#L12

The [Travis CI `ENOSPC` failures](https://travis-ci.org/floatdrop/gulp-watch/jobs/320313402#L677) seem to point to resource constraints and relate to gulpjs/gulp#217 / [stackoverflow.com/q/16748737](https://stackoverflow.com/q/16748737).

**Comment by phated** [comment]
@namoscato We've been using `npm@^3` for gulp projects.

**Comment by phated** [comment]
@floatdrop @UltCombo any word on when this will get updated?

**Comment by floatdrop** [comment]
@phated we need to check why `ENOSPC` happens – tests are not watching so many files.

**Comment by floatdrop** [comment]
Gulp.js is still on `3.9.1` version, so we can publish updated vinyl only on `latest` tag (as gulp does).

**Comment by phated** [comment]
Vinyl 2.1 is released as latest and is backwards compatible. This **needs** to get updated because the gulp 4 release is only a few days away.

**Comment by floatdrop** [comment]
> Vinyl 2.1 is released as latest and is backwards compatible. This needs to get updated because the gulp 4 release is only a few days away.

@phated I understand that, but still this should be released as major bump or with custom tags. I'm preferring bumping major versions for this. @UltCombo any thoughts on this?

**Comment by phated** [comment]
I think bumping major is good. But you probably want to wait for the upcoming chokidar v2 then. I'll be working on that tomorrow.

**Comment by phated** [comment]
@floatdrop chokidar bumped to 2.0 the other day.  Want to get that + vinyl 2.1 merged into master and major bump?

**Comment by phated** [comment]
Ping again @floatdrop

**Pull request merged**
