### PR TITLE
chore: update dependencies and apply new ES Lint rules

### PR DESCRIPTION
**Pull request by galuszkak**
Hi @floatdrop ,

Thanks for awesome package! I put some effort to update dependencies and apply new ESLint rules. 

I've also changed Travis NodeJS version to only have LTS versions that are supported (Linux and Windows OS).

I'm not sure why appveyor is not working, that's why I added windows build in Travis.

Thanks

### CODE REVIEW

**Comment by galuszkak** [comment]
Hi @floatdrop,

Kind reminder. Would you have time to review and merge this & release a new version?

**Comment by galuszkak** [comment]
Thanks @floatdrop . Will you be releasing new version?

**Comment by livehtml** [comment]
@floatdrop are looking forward to new release! ;)

**Comment by 3cp** [comment]
Any plan for a new release?

**Comment by philmayfield** [comment]
It would be great to see this released to resolve some CVEs that have popped up.

**Pull request merged**
